name: Rust

on:
  push:
    branches: [ master, make-fallible, utc-timestamps, utc-copy-truncate ]
  pull_request:
    branches: [ master, make-fallible ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check
      run: cargo check
  test:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        include:
          - os: macos-latest
          - os: ubuntu-latest
          - os: windows-latest
          - os: ubuntu-latest
            timezone: America/New_York
    env:
      TZ: ${{ matrix.timezone || 'UTC' }}
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: cargo test --all-features
